# Generated by Django 3.2.23 on 2024-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('order', 'Order Tracking'), ('order', 'Order Issue'), ('general', 'General Query'), ('complaint', 'Complaint'), ('return', 'Return Request')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=700)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Form',
            },
        ),
    ]
